# Generated by Django 4.1.2 on 2022-10-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
