# Generated by Django 4.1.2 on 2022-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(null=True, related_name='student_modules', to='app.module'),
        ),
    ]
