# Generated by Django 4.1.2 on 2022-10-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_first_name_user_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='first_names',
        ),
    ]
