# Generated by Django 4.1.2 on 2022-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_first_name_user_first_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_names',
            field=models.CharField(max_length=128),
        ),
    ]
