# Generated by Django 4.1.2 on 2022-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_first_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(related_name='student_modules', to='app.module'),
        ),
    ]
