# Generated by Django 4.1.2 on 2022-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_title',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
