# Generated by Django 4.1.2 on 2022-10-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_course_code_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modules',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollment', to='app.course')),
                ('modules', models.ManyToManyField(related_name='enrollment_modules', to='app.module')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollment', to='app.enrollment'),
        ),
    ]
