# Generated by Django 4.1.2 on 2022-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_modules_enrollment_user_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(related_name='course_modules', to='app.module'),
        ),
    ]
