# Generated by Django 4.1.2 on 2022-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_course_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
